# based on https://github.com/openanalytics/shinyproxy-demo/blob/master/application.yml
proxy:
  title: "Open Analytics ShinyProxy"
  logo-url: https://www.openanalytics.eu/shinyproxy/logo.png 
  template-path: ./layout
  landing-page: /
  heartbeat-rate: 10000
  heartbeat-timeout: 60000
  container-wait-time: 30000
  port: 8080
  docker:
    internal-networking: true
  authentication: simple
  admin-groups: admin
  users:
  - name: admin
    password: password
    groups: admin
  - name: crm
    password: password
    groups: crm
  specs:
  - id: ide_rstudio
    display-name: RStudio
    description: RStudio
    template-properties:
        tags: ide secondExampleTag
    container-image: openanalytics/shinyproxy-rstudio-ide-demo:2021.09.2_382__4.1.2
    container-env:
      DISABLE_AUTH: true
      WWW_ROOT_PATH: "#{proxy.getRuntimeValue('SHINYPROXY_PUBLIC_PATH')}"
    port: 8787
    container-network: shinyproxy-network
  - id: db_rmarkdowns
    display-name: RMarkdowns
    description: You can render RMarkdowns reports easily
    template-properties:
        tags: db
    container-image: demo_r_project:latest
    container-cmd: ["R", "-e", "rmarkdown::run('inst/markdowns/demo_example.Rmd', shiny_args=list(port=3838, host='0.0.0.0'))"] 
    container-network: shinyproxy-network
  - id: db_shiny
    display-name: RShiny
    description: You can render RShiny dashboards easily
    template-properties:
        tags: db
    container-cmd: ["R", "-e", "shinyproxy::run_01_hello()"]
    container-image: openanalytics/shinyproxy-demo
    container-network: shinyproxy-network
  - id: db_tableau
    display-name: Tableau Example
    description: "Public Dashboard Project Management Summary"
    template-properties:
        tags: db
    container-image: scaledbi-demo-tableau:latest
    container-env:
      DASHBOARD: PROJECTMANAGEMENTDASHBAORD/PROJECTMANAGEMENTSUMMARY
    port: 80
    container-network: shinyproxy-network
  usage-stats-url: jdbc:postgresql://192.168.11.2/db
  usage-stats-username: shinyproxy # "${POSTGRES_USERNAME}"
  usage-stats-password: password # "${POSTGRES_PASSWORD}"
logging:
  file:
    name: shinyproxy.log