# based on https://github.com/openanalytics/shinyproxy-demo/blob/master/application.yml
proxy:
  title: ScaledBI
  logo-url: https://www.openanalytics.eu/shinyproxy/logo.png
  landing-page: /
  heartbeat-rate: 10000
  heartbeat-timeout: 60000
  container-wait-time: 30000
  port: 8080
  docker:
    internal-networking: true
  authentication: simple
  admin-groups: admin
  users:
  - name: admin
    password: password
    groups: admin
  - name: crm
    password: password
    groups: crm
  specs:
  - id: ide_rstudio # https://github.com/ScaledBI/shinyproxy-rstudio-ide-demo
    display-name: RStudio
    description: RStudio
    container-image: openanalytics/shinyproxy-rstudio-ide-demo:2021.09.2_382__4.1.2
    container-env:
      DISABLE_AUTH: true
      WWW_ROOT_PATH: "#{proxy.getRuntimeValue('SHINYPROXY_PUBLIC_PATH')}"
    port: 8787
    container-network: shinyproxy-network
  - id: 01_hello
    display-name: Hello Application
    description: Application which demonstrates the basics of a Shiny app
    container-cmd: ["R", "-e", "shinyproxy::run_01_hello()"]
    container-image: openanalytics/shinyproxy-demo
    container-network: shinyproxy-network
  - id: 06_tabsets
    container-cmd: ["R", "-e", "shinyproxy::run_06_tabsets()"]
    container-image: openanalytics/shinyproxy-demo
    container-network: shinyproxy-network
  - id: ide_zeppelin
    display-name: Apache Zeppelin
    description: "Apache Zeppelin Notebooks"
    container-image: scaledbi-demo-zeppelin:latest
    container-network: shinyproxy-network
    port: 8080
  - id: db_tableau
    display-name: Tableau Example
    description: "Tableau Example: Public Dashboard Project Management Summary"
    container-image: scaledbi-demo-tableau:latest
    container-env:
      DASHBOARD: PROJECTMANAGEMENTDASHBAORD/PROJECTMANAGEMENTSUMMARY
    port: 80
    container-network: shinyproxy-network
  - id: db_jupyter
    display-name: Jupyter Demo
    description: "Example Jupyter Notebook"
    container-image: scaledbi-demo-jupyter:latest
    container-cmd: ["./start-notebook-as-html.sh", "notebooks/demo.ipynb"]
    port: 8000
    container-network: shinyproxy-network
  usage-stats-url: jdbc:postgresql://192.168.11.2/db
  usage-stats-username: shinyproxy # "${POSTGRES_USERNAME}"
  usage-stats-password: password # "${POSTGRES_PASSWORD}"
logging:
  file:
    name: shinyproxy.log
